# docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    image: js-web
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=file:/data/dev.db
      - UPLOADS_DIR=/uploads
      - ALLOWED_EMAILS=florianstoeffler1@gmail.com
    volumes:
      - app-data:/srv/upload/js-web
      - app-uploads:/srv/upload/js-web/project-images

volumes:
  app-data:
  app-uploads: