# docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    image: js-web
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=file:/srv/upload/js-web/prod.db
      - UPLOADS_DIR=/srv/upload/js-web/project-images
      - ALLOWED_EMAILS=florianstoeffler1@gmail.com
    volumes:
      - ./srv/upload/js-web:/srv/upload/js-web

# Using a host bind mount for /srv/upload/js-web so files persist outside container